### ISSUE TITLE
2048 tile does not generate

### ISSUE THREAD

**Issue by Kanelmis** [se310-Team4/KKDZ#94]
**Description**
When two 1024 tiles are merged, a 2048 tile will not be generated. Instead, an alert message is displayed. Dismissing the alert message resets the game. 

**Steps to reproduce**
1. Find `2048-expert/index.js `
2. Add the following lines of code to the end of the file
```
cells[0].innerHTML = 1024
cells[1].innerHTML = 1024
addColours()
```
4. Visit `http://localhost:1234/2048-expert/index.html`
5. Use the left arrow key to merge the two newly added tiles

**Expected behaviour**
A tile with 2048 should generate and an alert message should show

**Actual behaviour**
Alert message shows but the tiles remain unmerged 

**Potential cause**
The `alert()` function might be pausing the execution of other code, including the code that merges the two 1024 cells.

**Comment by Destiny-02** [comment]
Approved and reproducible
![image](https://user-images.githubusercontent.com/78716153/185142068-dde3c1ee-7fed-460e-803c-8d30712723f2.png)

**Comment by k-yle** [comment]
approved. I failed at 1024 so I couldn't reproduce it :)

**Comment by JosiahBull** [comment]
Note that this bug is browser-specific, and several other graphical glitches appear on Firefox.

Firefox:
![image](https://user-images.githubusercontent.com/29187591/192763426-9e8b9a7c-5a90-4c95-9fd1-fb22cd82e0b4.png)

Chrome:
![image](https://user-images.githubusercontent.com/29187591/192763597-93588736-a7c4-4b4f-9e55-7bfc7e618bab.png)
